apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      # 🌟 新增：告诉 K8s 去哪里拿拉取镜像的钥匙
      containers:
        - name: app
          # 这里会自动读取你 values.yaml 里的阿里云 ACR 地址
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # 这里会自动读取 values.yaml 里的 1C2G 降配设置
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
